name: Testing

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repo with LFS
      uses: actions/checkout@v4
      with:
        lfs: true
    - name: Setup Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Set up uv
      uses: astral-sh/setup-uv@v1
      with:
        version: 'latest'
    - name: Set up uv cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/uv
        key: ${{ runner.os }}-uv-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-uv-
    - name: Create and Activate Virtual Environment
      run: |
        uv venv .venv
        echo "VIRTUAL_ENV=.venv" >> $GITHUB_ENV
        echo "$PWD/.venv/bin" >> $GITHUB_PATH
    - name: Install Python project dependencies
      run: uv pip install -r requirements.txt
    - name: Install Python dev dependencies
      run: uv pip install -r requirements-dev.txt
    - name: Execute tests
      run: pytest tests/ -v
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: results/*.csv
