name: Testing

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - run: pip install uv
    - run: uv pip install --system -r requirements.txt
    - run: uv pip install --system -r requirements-dev.txt
    - run: pytest tests/ -v
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: results/*.csv
