name: Testing

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repo
      uses: actions/checkout@v4

    - name: Setup Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Python project dependencies
      run: pip install -r requirements.txt

    - name: Install Python dev dependencies
      run: pip install -r requirements-dev.txt

    - name: Execute tests
      run: pytest tests/ -v
      
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: results/*.csv
